# Generated by Django 5.0.4 on 2024-05-16 14:21

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_count_userbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='borrowed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 14, 21, 52, 455608, tzinfo=datetime.timezone.utc)),
        ),
    ]
