# Generated by Django 5.0.4 on 2024-05-21 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_userbook_borrowed_date_userbook_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='book_pdfs/'),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 21, 3, 37, 697162, tzinfo=datetime.timezone.utc)),
        ),
    ]
