# Generated by Django 5.0.4 on 2024-06-15 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_book_pdf_file_alter_userbook_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 25, 7, 17, 15, 296306, tzinfo=datetime.timezone.utc)),
        ),
    ]
