# Generated by Django 5.0.4 on 2024-09-13 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_userbook_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 4, 6, 49, 536384, tzinfo=datetime.timezone.utc)),
        ),
    ]
